Repository gesund-ai/gesund, pull requests merged in 2024-12, with the labels that each got.

#42 ref (metrics): Classification Metrics Update Following Planned Methodology
  gesund/core/__init__.py
  gesund/core/_metrics/common/auc.py
  gesund/core/_metrics/common/confusion_matrix.py
  gesund/core/_metrics/common/lift_chart.py
  gesund/core/_metrics/common/most_confused.py
  gesund/core/_metrics/common/stats_tables.py
  gesund/core/_metrics/common/threshold.py
  gesund/core/_metrics/common/top_losses.py
  gesund/validation/_result.py
  gesund/validation/_validation.py
  tests/conftest.py
  tests/validation/test_validation.py
Labels: enhancement, v0.1.4

#50 refactor(core): added segmentation metrics
  gesund/core/__init__.py
  gesund/core/_metrics/common/confidence_distribution.py
  gesund/core/_metrics/common/dice.py
  gesund/core/_metrics/common/dice_distribution.py
  gesund/core/_metrics/common/iou.py
  gesund/core/_metrics/common/iou_distribution.py
  gesund/core/_metrics/common/predicted_distribution.py
  gesund/core/_metrics/common/threshold.py
  tests/core/test_manager.py
  tests/validation/test_validation.py
Labels: refactor

#51 refactor(core): added top losses for semantic segmentation
  gesund/core/_metrics/common/dice.py
  gesund/core/_metrics/common/dice_distribution.py
  gesund/core/_metrics/common/top_losses.py
  tests/validation/test_validation.py
Labels: enhancement

#52 refactor(gesund): minor refactor
  pyproject.toml
  setup.py
Labels: refactor
