Repository gesund-ai/gesund, pull requests merged in 2024-11, with the labels that each got.

#4 Added notebook
  gesund/notebooks/ObjectDetection.ipynb
  gesund/notebooks/Segmentation.ipynb
Labels: enhancement

#5 updates for notebooks
  gesund/examples/classification_covidnet.ipynb
  gesund/examples/object_detection_malaria.ipynb
  gesund/examples/semantic_segmentation_brain_cancer.ipynb
  gesund/notebooks/Segmentation.ipynb
  gesund/notebooks/classification.ipynb
  gesund/notebooks/fairness.ipynb
  gesund/notebooks/object_detection.ipynb
  gesund/notebooks/semantic_segmentation.ipynb
Labels: enhancement

#6 fix:remove minor naming error
  gesund/examples/classification_covidnet.ipynb
  gesund/examples/object_detection_malaria.ipynb
  gesund/examples/semantic_segmentation_brain_cancer.ipynb
Labels: bug

#7 fix:bug colab tab
  gesund/examples/classification_covidnet.ipynb
  gesund/examples/object_detection_malaria.ipynb
  gesund/examples/semantic_segmentation_brain_cancer.ipynb
Labels: bug

#22 Test scripts for _plot & _conversations and also for other test cases
  tests/core/__init__.py
  tests/core/_converters.py
  tests/core/_plot.py
  tests/core/_test_integration.py
Labels: enhancement

#24 refactor project toml file correctly update with pycoco format error fix
  pyproject.toml
Labels: bug

#26 ref: Update readme file
  README.md
  gesund/assets/gesund_logo.png
Labels: documentation

#28 fix:semantic segmentation small bug
  gesund/core/_metrics/classification/create_validation.py
  gesund/core/_metrics/object_detection/create_validation.py
  gesund/core/_metrics/semantic_segmentation/create_validation.py
  gesund/core/_metrics/semantic_segmentation/plots/plot_driver.py
  gesund/validation/_validation.py
  tests/validation/__init__.py
Labels: bug

#23 ref: Update typing hints for all structure
  gesund/core/_converters/coco_converter.py
  gesund/core/_metrics/classification/create_validation.py
  gesund/core/_metrics/classification/metrics/accuracy.py
  gesund/core/_metrics/classification/metrics/auc.py
  gesund/core/_metrics/classification/metrics/confusion_matrix.py
  gesund/core/_metrics/classification/metrics/dataset_stats.py
  gesund/core/_metrics/classification/metrics/lift_chart.py
  gesund/core/_metrics/classification/metrics/most_confused.py
  gesund/core/_metrics/classification/metrics/stats_tables.py
  gesund/core/_metrics/classification/metrics/threshold.py
  gesund/core/_metrics/classification/metrics/top_losses.py
  gesund/core/_metrics/object_detection/create_validation.py
  gesund/core/_metrics/object_detection/plots/average_precision.py
  gesund/core/_metrics/object_detection/plots/confidence_distribution.py
  gesund/core/_metrics/object_detection/plots/dataset_stats.py
  gesund/core/_metrics/object_detection/plots/object_stats.py
  gesund/core/_metrics/object_detection/plots/plot_driver.py
  gesund/core/_metrics/object_detection/plots/top_losses.py
  gesund/core/_metrics/semantic_segmentation/create_validation.py
Labels: documentation

#8 refactor(coco_converter): re-designed the code to include consistency of pattern
  gesund/core/_converters/coco_converter.py
Labels: documentation
